'use client';

import { useState, useEffect } from 'react';
import { Loader2, Check, AlertCircle } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { usePatient } from '@/contexts/PatientContext';

// Define a mock AI analysis process that simulates generating a psychological report
interface AIAnalysisProcessProps {
  onAnalysisComplete: (draftText: string) => void;
  areasEvaluacion: string[];
  criteriosCIE: string[];
  motivosConsulta: string[];
}

export function AIAnalysisProcess({
  onAnalysisComplete,
  areasEvaluacion,
  criteriosCIE,
  motivosConsulta
}: AIAnalysisProcessProps) {
  const { currentPatient } = usePatient();
  const [progress, setProgress] = useState(0);
  const [currentPhase, setCurrentPhase] = useState('Preparando datos del paciente...');
  const [error, setError] = useState<string | null>(null);
  
  // Phases of the analysis process
  const phases = [
    'Preparando datos del paciente...',
    'Analizando motivos de consulta...',
    'Evaluando áreas psicológicas...',
    'Correlacionando con criterios CIE-11...',
    'Generando borrador de informe...',
    'Refinando contenido...',
    'Completando documento final...'
  ];
  
  useEffect(() => {
    if (!currentPatient) {
      setError('No se ha seleccionado un paciente');
      return;
    }
    
    let currentPhaseIndex = 0;
    const totalPhases = phases.length;
    const phaseTime = 1000; // Time per phase in ms
    
    // Start the analysis process
    setCurrentPhase(phases[0]);
    
    // Simulate AI processing through each phase
    const processInterval = setInterval(() => {
      if (currentPhaseIndex < totalPhases - 1) {
        currentPhaseIndex++;
        setCurrentPhase(phases[currentPhaseIndex]);
        setProgress(Math.floor((currentPhaseIndex / (totalPhases - 1)) * 100));
      } else {
        // Complete the process
        clearInterval(processInterval);
        setProgress(100);
        
        // Generate a mock report based on the provided data
        generateMockReport();
      }
    }, phaseTime);
    
    return () => clearInterval(processInterval);
  }, [currentPatient]);
  
  // Generate a mock psychological report based on the provided data
  const generateMockReport = () => {
    // Mock report template - in a real app this would be generated by an AI service
    const patientName = currentPatient?.name || 'Paciente';
    const patientId = currentPatient?.id || 'ID-Unknown';
    
    // Sample report text based on the selected areas and criteria
    const areasText = areasEvaluacion.map(area => {
      switch(area) {
        case 'cognitiva':
          return 'En la evaluación de la función cognitiva, el paciente muestra capacidades dentro del rango esperado en atención, memoria y razonamiento.';
        case 'emocional':
          return 'Se observa cierta dificultad en la regulación emocional, particularmente en situaciones de estrés agudo.';
        case 'conductual':
          return 'Los patrones conductuales muestran adaptación adecuada en entornos estructurados, pero cierta dificultad en situaciones menos previsibles.';
        default:
          return `Se realizó evaluación del área ${area}.`;
      }
    }).join('\n\n');
    
    const criteriosText = criteriosCIE.map(criterio => {
      return `De acuerdo con los criterios CIE-11, se observan características compatibles con ${criterio}.`;
    }).join('\n\n');
    
    const motivosText = motivosConsulta.join(', ');
    
    // Assemble the complete report
    const reportDraft = `
# INFORME PSICOLÓGICO

## DATOS DE IDENTIFICACIÓN
**Paciente:** ${patientName}
**ID:** ${patientId}

## MOTIVO DE CONSULTA
El paciente acude por: ${motivosText}

## ÁREAS EVALUADAS
${areasText}

## DIAGNÓSTICO
${criteriosText}

## CONCLUSIONES Y RECOMENDACIONES
Basado en la evaluación realizada, se recomienda un seguimiento terapéutico enfocado en las áreas identificadas de mejora. Se sugiere un enfoque de terapia cognitivo-conductual, con sesiones semanales durante un período inicial de 12 semanas.

## PLAN DE TRATAMIENTO
1. Psicoeducación sobre el diagnóstico identificado
2. Desarrollo de habilidades de afrontamiento y regulación emocional
3. Restructuración cognitiva de patrones de pensamiento desadaptativos
4. Establecimiento de rutinas y hábitos saludables

Este informe es de carácter confidencial y debe ser utilizado sólo por profesionales de la salud mental autorizados.
`;
    
    // Pass the generated report to the parent component
    onAnalysisComplete(reportDraft);
  };
  
  if (error) {
    return (
      <Card className="p-6 bg-red-50 border-red-200">
        <div className="flex items-center space-x-3">
          <AlertCircle className="h-6 w-6 text-red-500" />
          <div>
            <h3 className="font-medium text-red-800">Error en el análisis</h3>
            <p className="text-sm text-red-600">{error}</p>
          </div>
        </div>
      </Card>
    );
  }
  
  return (
    <Card className="p-6">
      <div className="space-y-4">
        <h3 className="text-lg font-medium">Análisis IA en proceso</h3>
        <p className="text-sm text-gray-600">
          Nuestro sistema está analizando la información del paciente para generar un borrador de informe.
        </p>
        
        <div className="space-y-2">
          <div className="flex justify-between text-sm">
            <span>{currentPhase}</span>
            <span>{progress}%</span>
          </div>
          <Progress value={progress} className="h-2" />
        </div>
        
        <div className="flex items-center space-x-2 text-blue-600">
          <Loader2 className="h-4 w-4 animate-spin" />
          <span className="text-sm">Procesando datos clínicos</span>
        </div>
      </div>
    </Card>
  );
} 